[install]
optional = true
dev = true
peer = true
production = false
frozenLockfile = true
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN"}


[test]
smol = true
coverage = true
coverageThreshold = { line = 0.0, function = 0.0, statement = 0.0 }
coverageSkipTestFiles = false
