packages:
  - packages/*
  - apps/*

catalogs:
  dev:
    tsdown: ^0.12.9
    tsx: ^4.20.3
    unplugin-vue: ^6.2.0
    vue-tsc: ^2.2.10
    '@primeuix/themes': ^1.1.2
    '@vueuse/core': ^13.4.0
    'primevue': ^4.3.5
    'vue-types': ^6.0.0
    '@apollo/client': ^3.13.8
    '@vue/apollo-composable': ^4.2.2
