packages:
  - packages/*
  - apps/*

catalogs:
  dev:
    '@antfu/eslint-config': ^3.16.0
    '@apollo/client': ^3.14.0
    '@primeuix/themes': ^1.2.5
    '@types/fs-extra': ^11.0.4
    '@typescript-eslint/eslint-plugin': ^8.46.2
    '@typescript-eslint/parser': ^8.46.2
    '@typescript-eslint/type-utils': ^8.46.2
    '@typescript-eslint/types': ^8.46.2
    '@typescript-eslint/typescript-estree': ^8.46.2
    '@typescript-eslint/utils': ^8.46.2
    '@vue/apollo-composable': ^4.2.2
    '@vueuse/core': ^14.0.0
    eslint: ^9.39.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-vue: ^9.33.0
    fs-extra: ^11.3.2
    prettier: ^3.6.2
    primevue: ^4.4.1
    rolldown-plugin-dts: ^0.17.3
    simple-git-hooks: ^2.13.1
    taze: ^0.16.9
    tsdown: ^0.12.9
    tsx: ^4.20.6
    typescript: ^5.8.3
    unplugin-vue: ^6.2.0
    vue: ^3.5.22
    vue-tsc: ^2.2.12
    vue-types: ^6.0.0

ignoredBuiltDependencies:
  - simple-git-hooks
